apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-staging-deployment
  labels:
    app: crawler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: "gcr.io/<YOUR_PROJECT_ID>/crawler-app:latest"
        ports:
        - containerPort: 8080