apiVersion: apps/v1
kind: Deployment
metadata:
  name: bay-crawler-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bay-crawler
  template:
    metadata:
      labels:
        app: bay-crawler
    spec:
      containers:
      - name: bay-crawler
        image: bay-crawler-image
        ports:
        - containerPort: 8080
        env:
        - name: CLOUD_SQL_CONNECTION_NAME
          value: "${PROJECT_ID}:us-central1:bay-crawler-sql-instance"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bay-crawler-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bay-crawler-secret
              key: password