name: Crawler CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        # Here you would run your test suite
        echo "Running tests..."
    - name: Build Docker image
      run: |
        docker build -t my-crawler .
    - name: Push Docker image
      run: |
        # Here you would push your Docker image to a registry
        echo "Pushing Docker image..."